version: '3.8'

services:
  # --- THE BACKEND ---
  drive-server:
    build: ./backend
    container_name: drive_backend
    ports:
      - "50051:50051"
      - "8080:8080" # REST Port (Important for the frontend!)
    depends_on:
      - postgres
      - minio
      - rabbitmq # Added RabbitMQ dependency
      - redis # Added Redis dependency
    environment:
      DB_URL: jdbc:postgresql://drive_db:5432/minidrive
      MINIO_ENDPOINT: http://drive_storage:9000
      RABBITMQ_HOST: drive_queue
      REDIS_HOST: drive_cache

  # --- INFRASTRUCTURE ---
  postgres:
    image: postgres:15-alpine
    container_name: drive_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: minidrive
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: drive_storage
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: drive_queue
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: drive_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes # Enable AOF persistence

volumes:
  postgres_data:
  minio_data:
  rabbitmq_data:
  redis_data:
